@startuml

interface OrderProcessor {
  + ship(): void
  + bill(): void
}

class OnlineOrder {
  + ship(): void
  + bill(): void
}

class InStoreOrder implements OrderProcessor {
  + ship(): void
  + bill(): void
}
note left of InStoreOrder
    ship() is not
    applicable
    in store
end note

OnlineOrder .right.|> OrderProcessor

@enduml