@startuml
class Employee {
  - String name
  - double salary
  + Employee(String name, double salary)
  + getName(): String
  + setName(String name): void
  + getSalary(): double
  + setSalary(double salary): void
  + saveEmployeeToFile(): void
  + calculateSalaryIncrement(): void
}
@enduml