@startuml

interface Billable {
  + bill(): void
}

interface Shippable {
  + ship(): void
}

class OnlineOrder implements Shippable, Billable {
  + ship(): void
  + bill(): void
}

class InStoreOrder implements Billable {
  + bill(): void
}

@enduml