@startuml

interface ProductOwnerActivities {
  +refineBacklog()
  +communicateStakeholder()
}

interface ScrumMasterActivities {
  +facilitateScrumEvent()
  +removeImpediment()
}

interface DeveloperActivities {
  +implementUserStory()
  +deploySolution()
}

class ProductOwner implements ProductOwnerActivities{
  +refineBacklog()
  +communicateStakeholder()
}

class ScrumMaster implements ScrumMasterActivities{
  +facilitateScrumEvent()
  +removeImpediment()
}

class Developer implements DeveloperActivities{
  +implementUserStory()
  +deploySolution()
}

@enduml