@startuml

abstract class Employee {
  - fullname: String
  - hoursWorked: int
  + Employee(fullname: String,hoursWorked: int)
  + getFullname(): String
  + getHoursWorked(): int
  + abstract calculateSalary(): double
}

class EmployeeFulltime extends Employee {
  + EmployeeFulltime(fullname: String,
  hoursWorked: int, extraHours: int)
}

class EmployeeContrator extends Employee {
  + EmployeeContrator(fullname: String,
  hoursWorked: int)
}
note right of Employee
    calculateSalary is implemented
    on each subclass, control
    flag is not needed
end note

@enduml